# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty
relative_permalinks: true

# Setup
title:            Hyde
tagline:          'TheBeekeeper'
description:      'A Webpage about beekeeping in the US'
url:              https://dpepoon.github.io/TheBeekeeper/
baseurl:          https://dpepoon.github.io/TheBeekeeper/

author:
  name:           'Dale Pepoon'
  url:            

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/TheBeekeeper
