# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty


# Setup
title:            TheBeekeeper
tagline:          'TheBeekeeper'
description:      'A Webpage about beekeeping in the US'
url:              https://dpepoon.github.io
baseurl:          /TheBeekeeper

author:
  name:           'Dale Pepoon'
  url:            

gems: [jekyll-paginate]
paginate: 5
paginate_path: "page:num"

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/dpepoon/TheBeekeeper
